# This is a basic workflow that is manually triggered

name: Test Primer

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      fwd:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Forward Primer'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      reve:
        description: 'Reverse Primer'
        default: ''
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  primer-eval:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Source Code
      uses: actions/checkout@v5
      with:
        repository: EndCredits/primer-eval
        ref: main
        path: primer-eval

    - name: Setup Python
      run: |
        sudo apt -y update
        sudo apt -y install python3 python-is-python3
        python -m venv primer-venv
        source ./primer-venv/bin/activate
        pip install primer3-py

    - name: Run Evaluation
      run: |
        source ./primer-venv/bin/activate
        cd primer-eval
        python primer-eval.py "${{ inputs.fwd }}" "${{ inputs.reve }}"
